### PR TITLE
General Improvements-revised

### PR DESCRIPTION
**Pull request by VeriskPuppet**
* improved checks for registration and enabled repository
* created fact for enabled rhsm repos
* wider testing

### CODE REVIEW

**Comment by VeriskPuppet** [comment]
We were a bit excited to push out our first Patch. We have resubmitted with a few fixes.

**Comment by gerapeldoorn** [comment]
Hi, Sorry for the delay.

I've been waiting for an opp. to test it, which i'll do tomorrow. Is this
patch still current?

Ger

*Ger Apeldoorn*
Freelance Puppet consultant/trainer

Swalmstraat 1
8303 JD Emmeloord
The Netherlands
*Mobile:* +31 6 46424945
*Email:* info@gerapeldoorn.nl
*Website: http://puppetspecialist.nl <http://puppetspecialist.nl>*
*Website: http://autiplan.nl <http://autiplan.nl>*
*Website: http://mijneigenplan.nl <http://mijneigenplan.nl>*

[image: LinkedIn] <http://www.linkedin.com/in/gerapeldoorn>[image: Twitter]
<https://twitter.com/gerapeldoorn>[image: Google+]
<https://plus.google.com/112857204167622817442/posts>


2015-11-22 1:08 GMT+01:00 VeriskPuppet <notifications@github.com>:

**Comment by tux-o-matic** [comment]
Improved indeed. How about making 'force' an option and link that behaviour to the 'RHNSM-register' Exec?

**Comment by VeriskPuppet** [comment]
Yes this patch is still current, we're running it in production

**Comment by gerapeldoorn** [comment]
My apologies for the delays. I'm not in a position to test your updates,
feel free to publish it on the forge, I'll deprecate mine in favor of yours.

Thanks,
Ger

*Ger Apeldoorn*
Freelance Puppet consultant/trainer

Swalmstraat 1
8303 JD Emmeloord
The Netherlands
*Mobile:* +31 6 46424945
*Email:* info@gerapeldoorn.nl
*Website: http://puppetspecialist.nl <http://puppetspecialist.nl>*
*Website: http://autiplan.nl <http://autiplan.nl>*
*Website: http://mijneigenplan.nl <http://mijneigenplan.nl>*

[image: LinkedIn] <http://www.linkedin.com/in/gerapeldoorn>[image: Twitter]
<https://twitter.com/gerapeldoorn>[image: Google+]
<https://plus.google.com/112857204167622817442/posts>


2016-02-04 22:50 GMT+01:00 VeriskPuppet <notifications@github.com>:

**Comment by tux-o-matic** [comment]
@gerapeldoorn Can you maybe transfer this project other to the Puppet Community repo?

**Pull request merged**
